-- Inserindo mais dados na tabela de produtos
INSERT INTO produtos (nome, preco) VALUES
    ('Boné', 14.99),
    ('Óculos de Sol', 39.99),
    ('Bolsa', 49.99),
    ('Cinto', 19.99),
    ('Chapéu', 24.99),
    ('Gravata', 29.99),
    ('Relógio', 99.99),
    ('Carteira', 34.99),
    ('Brinco', 9.99),
    ('Colar', 19.99),
    ('Pulseira', 14.99),
    ('Anel', 29.99),
    ('Sapato Social', 79.99),
    ('Tênis', 54.99),
    ('Bota', 69.99),
    ('Sandália', 39.99),
    ('Chinelo', 19.99),
    ('Bermuda', 24.99),
    ('Saia', 29.99),
    ('Vestido', 49.99),
    ('Blusa', 34.99),
    ('Blazer', 69.99),
    ('Jaqueta', 59.99),
    ('Casaco', 79.99),
    ('Sobretudo', 99.99),
    ('Calça Jeans', 44.99),
    ('Calça Social', 54.99),
    ('Shorts', 19.99),
    ('Meia-Calça', 14.99),
    ('Camiseta', 19.99),
    ('Camisa Polo', 29.99),
    ('Camisa Social', 39.99),
    ('Camisa Xadrez', 34.99),
    ('Regata', 14.99),
    ('Macacão', 49.99),
    ('Jardineira', 39.99),
    ('Colete', 29.99),
    ('Suéter', 39.99),
    ('Cardigã', 44.99),
    ('Moletom', 34.99),
    ('Blusão', 29.99),
    ('Parka', 79.99),
    ('Macacão Jeans', 59.99),
    ('Macacão Social', 69.99),
    ('Vestido de Festa', 89.99),
    ('Gravata Borboleta', 19.99),
    ('Lenço', 9.99),
    ('Calça Legging', 19.99),
    ('Shorts Jeans', 24.99),
    ('Top', 14.99),
    ('Cropped', 19.99),
    ('Blusa de Frio', 39.99),
    ('Blusa de Tricô', 29.99),
    ('Blusa de Alça', 14.99),
    ('Suéter de Tricô', 49.99),
    ('Kimono', 59.99),
    ('Jaqueta Jeans', 44.99),
    ('Colete Jeans', 34.99),
    ('Jaqueta de Couro', 89.99),
    ('Trench Coat', 79.99),
    ('Sobretudo de Lã', 109.99),
    ('Suéter de Lã', 59.99),
    ('Cardigã de Lã', 49.99),
    ('Blusa de Lã', 39.99),
    ('Blusão de Lã', 54.99),
    ('Macacão de Lã', 69.99),
    ('Vestido de Lã', 79.99),
    ('Jaqueta de Lã', 89.99),
    ('Sobretudo de Cashmere', 129.99),
    ('Cardigã de Cashmere', 69.99),
    ('Blusa de Cashmere', 59.99),
    ('Suéter de Cashmere', 89.99),
    ('Jaqueta de Cashmere', 149.99),
    ('Sobretudo de Seda', 159.99),
    ('Vestido de Seda', 99.99),
    ('Blusa de Seda', 79.99),
    ('Camisa de Seda', 89.99),
    ('Lenço de Seda', 29.99),
    ('Gravata de Seda', 39.99),
    ('Cachecol de Seda', 49.99),
    ('Kimono de Seda', 129.99),
    ('Blazer de Seda', 159.99),
    ('Casaquinho de Seda', 79.99),
    ('Suéter de Seda', 119.99),
    ('Vestido de Noiva', 499.99),
    ('Vestido de Madrinha', 299.99),
    ('Terno de Noivo', 199.99),
    ('Terno de Padrinho', 149.99),
    ('Gravata de Noivo', 29.99),
    ('Gravata de Padrinho', 19.99),
    ('Sapato de Noivo', 149.99),
    ('Sapato de Madrinha', 99.99),
    ('Sapato de Padrinho', 79.99),
    ('Buquê de Noiva', 49.99),
    ('Corsage', 19.99);

-- Inserindo mais dados na tabela de clientes
INSERT INTO clientes (nome, email) VALUES
    ('Ana', 'ana@example.com'),
    ('Carlos', 'carlos@example.com'),
    ('Fernanda', 'fernanda@example.com'),
    ('Rafael', 'rafael@example.com'),
    ('Juliana', 'juliana@example.com'),
    ('Lucas', 'lucas@example.com'),
    ('Amanda', 'amanda@example.com'),
    ('Gabriel', 'gabriel@example.com'),
    ('Isabela', 'isabela@example.com'),
    ('Diego', 'diego@example.com'),
    ('Laura', 'laura@example.com'),
    ('Bruno', 'bruno@example.com'),
    ('Mariana', 'mariana@example.com'),
    ('Felipe', 'felipe@example.com'),
    ('Vanessa', 'vanessa@example.com'),
    ('Gustavo', 'gustavo@example.com'),
    ('Larissa', 'larissa@example.com'),
    ('Rodrigo', 'rodrigo@example.com'),
    ('Camila', 'camila@example.com'),
    ('Thiago', 'thiago@example.com'),
    ('Carolina', 'carolina@example.com'),
    ('Ricardo', 'ricardo@example.com'),
    ('Nathalia', 'nathalia@example.com'),
    ('Eduardo', 'eduardo@example.com'),
    ('Luiza', 'luiza@example.com'),
    ('Vinicius', 'vinicius@example.com'),
    ('Beatriz', 'beatriz@example.com'),
    ('Leonardo', 'leonardo@example.com'),
    ('Patrícia', 'patricia@example.com'),
    ('Guilherme', 'guilherme@example.com'),
    ('Sandra', 'sandra@example.com'),
    ('Pedro', 'pedro@example.com'),
    ('Fernando', 'fernando@example.com'),
    ('Vanessa', 'vanessa@example.com'),
    ('Roberto', 'roberto@example.com'),
    ('Leticia', 'leticia@example.com'),
    ('Miguel', 'miguel@example.com'),
    ('Ana Paula', 'anapaula@example.com'),
    ('Thais', 'thais@example.com'),
    ('Renato', 'renato@example.com'),
    ('Carla', 'carla@example.com'),
    ('Marcos', 'marcos@example.com'),
    ('Monica', 'monica@example.com'),
    ('Daniel', 'daniel@example.com'),
    ('Lorena', 'lorena@example.com'),
    ('Luciano', 'luciano@example.com'),
    ('Natalia', 'natalia@example.com'),
    ('Anderson', 'anderson@example.com'),
    ('Cristina', 'cristina@example.com'),
    ('Paulo', 'paulo@example.com'),
    ('Jessica', 'jessica@example.com'),
    ('Ronaldo', 'ronaldo@example.com'),
    ('Carolina', 'carolina@example.com'),
    ('Marcelo', 'marcelo@example.com'),
    ('Aline', 'aline@example.com'),
    ('Hugo', 'hugo@example.com'),
    ('Simone', 'simone@example.com'),
    ('Vinicius', 'vinicius@example.com'),
    ('Bruna', 'bruna@example.com'),
    ('Rafaela', 'rafaela@example.com'),
    ('Diego', 'diego@example.com'),
    ('Maria Eduarda', 'mariaeduarda@example.com'),
    ('Patricia', 'patricia@example.com'),
    ('Junior', 'junior@example.com'),
    ('Caroline', 'caroline@example.com'),
    ('Marcela', 'marcela@example.com'),
    ('Rodolfo', 'rodolfo@example.com'),
    ('Tatiane', 'tatiane@example.com'),
    ('Renata', 'renata@example.com'),
    ('Roberta', 'roberta@example.com'),
    ('Sergio', 'sergio@example.com'),
    ('Alessandra', 'alessandra@example.com'),
    ('Ricardo', 'ricardo@example.com'),
    ('Sabrina', 'sabrina@example.com'),
    ('Leandro', 'leandro@example.com'),
    ('Julia', 'julia@example.com'),
    ('Fabio', 'fabio@example.com'),
    ('Camila', 'camila@example.com'),
    ('Fernando', 'fernando@example.com'),
    ('Patricia', 'patricia@example.com'),
    ('Anderson', 'anderson@example.com'),
    ('Amanda', 'amanda@example.com'),
    ('Paulo', 'paulo@example.com'),
    ('Renata', 'renata@example.com'),
    ('Roberto', 'roberto@example.com'),
    ('Cristina', 'cristina@example.com'),
    ('Vinicius', 'vinicius@example.com'),
    ('Priscila', 'priscila@example.com'),
    ('Gabriel', 'gabriel@example.com'),
    ('Adriana', 'adriana@example.com');
